"""90-day quiz question bank. 10 questions per day, basic to expert.

TO ADD A DAY: copy a day block, change the number, write 10 questions.
Each question: {"q": "...", "options": [4 choices], "correct": index 0-3}
The engine auto-detects any day you add here. No other code changes needed.

Curve: Days 1-20 Beginner, 21-45 Intermediate, 46-70 Advanced, 71-90 Expert.
"""

QUIZ_DATA = {
    1: {"topic": "Python Basics — Intro", "questions": [
        {"q": "Which keyword defines a function in Python?", "options": ["func", "def", "function", "lambda"], "correct": 1},
        {"q": "How do you write a single-line comment?", "options": ["//", "#", "<!--", "/*"], "correct": 1},
        {"q": "Which is a valid variable name?", "options": ["2name", "my-name", "my_name", "my name"], "correct": 2},
        {"q": "What does print() do?", "options": ["Reads input", "Outputs to screen", "Deletes a file", "Adds numbers"], "correct": 1},
        {"q": "Which symbol is used for assignment?", "options": ["==", "=>", "=", ":="], "correct": 2},
        {"q": "What is the output of: print(2 + 3)?", "options": ["23", "5", "2 + 3", "Error"], "correct": 1},
        {"q": "Which is NOT a Python data type?", "options": ["int", "float", "char", "str"], "correct": 2},
        {"q": "How do you create a string?", "options": ["Quotes", "Brackets", "Braces", "Parentheses"], "correct": 0},
        {"q": "What does type() return?", "options": ["The value", "The data type", "The length", "The memory"], "correct": 1},
        {"q": "Python is which kind of language?", "options": ["Compiled only", "Interpreted", "Assembly", "Machine code"], "correct": 1},
    ]},
    2: {"topic": "Variables & Data Types", "questions": [
        {"q": "What type is True?", "options": ["int", "bool", "str", "float"], "correct": 1},
        {"q": "What is 7 // 2?", "options": ["3.5", "3", "4", "3.0"], "correct": 1},
        {"q": "What is 2 ** 3?", "options": ["6", "8", "9", "5"], "correct": 1},
        {"q": "What type is 3.14?", "options": ["int", "float", "str", "bool"], "correct": 1},
        {"q": "How do you convert '5' to an integer?", "options": ["str(5)", "int('5')", "float('5')", "bool('5')"], "correct": 1},
        {"q": "What is the result of 10 % 3?", "options": ["3", "1", "0", "3.33"], "correct": 1},
        {"q": "Which creates a float?", "options": ["x = 5", "x = '5'", "x = 5.0", "x = True"], "correct": 2},
        {"q": "What is None in Python?", "options": ["Zero", "Empty string", "Absence of value", "False"], "correct": 2},
        {"q": "What does str(42) produce?", "options": ["42", "'42'", "Error", "4.2"], "correct": 1},
        {"q": "Which is a valid boolean?", "options": ["true", "TRUE", "True", "yes"], "correct": 2},
    ]},
    3: {"topic": "Strings", "questions": [
        {"q": "How do you get the length of a string s?", "options": ["s.length", "len(s)", "size(s)", "s.size()"], "correct": 1},
        {"q": "What does 'abc'[0] return?", "options": ["a", "b", "c", "Error"], "correct": 0},
        {"q": "What does 'Hello'.upper() return?", "options": ["hello", "HELLO", "Hello", "hELLO"], "correct": 1},
        {"q": "How do you join 'a' and 'b'?", "options": ["'a' + 'b'", "'a' - 'b'", "'a' * 'b'", "'a' / 'b'"], "correct": 0},
        {"q": "What does 'abc'[-1] return?", "options": ["a", "c", "b", "Error"], "correct": 1},
        {"q": "What does 'Hi'.replace('i','ey') give?", "options": ["Hey", "Hi", "Hiey", "Hieey"], "correct": 0},
        {"q": "What does ' hi '.strip() return?", "options": ["' hi '", "'hi'", "'hi '", "' hi'"], "correct": 1},
        {"q": "What does 'a,b,c'.split(',') return?", "options": ["'abc'", "['a','b','c']", "('a','b','c')", "Error"], "correct": 1},
        {"q": "Are Python strings mutable?", "options": ["Yes", "No", "Sometimes", "Only short ones"], "correct": 1},
        {"q": "What does 'ab' * 3 return?", "options": ["'ababab'", "'ab3'", "Error", "'abababab'"], "correct": 0},
    ]},
    4: {"topic": "Lists — Basics", "questions": [
        {"q": "How do you create an empty list?", "options": ["[]", "{}", "()", "list{}"], "correct": 0},
        {"q": "How do you add to the end of a list?", "options": [".add()", ".append()", ".push()", ".insert()"], "correct": 1},
        {"q": "What does [1,2,3][1] return?", "options": ["1", "2", "3", "Error"], "correct": 1},
        {"q": "How do you remove the last item?", "options": [".pop()", ".remove()", ".delete()", ".cut()"], "correct": 0},
        {"q": "What does len([1,2,3]) return?", "options": ["2", "3", "4", "0"], "correct": 1},
        {"q": "Are lists mutable?", "options": ["Yes", "No", "Only numbers", "Only strings"], "correct": 0},
        {"q": "What does [1,2] + [3,4] give?", "options": ["[1,2,3,4]", "[4,6]", "Error", "[[1,2],[3,4]]"], "correct": 0},
        {"q": "How do you access the first item?", "options": ["list[1]", "list[0]", "list.first", "list(0)"], "correct": 1},
        {"q": "What does [5,3,1].sort() do?", "options": ["Reverses", "Sorts ascending", "Removes items", "Nothing"], "correct": 1},
        {"q": "What does 'x' in ['x','y'] return?", "options": ["True", "False", "0", "Error"], "correct": 0},
    ]},
    5: {"topic": "Operators & Conditionals", "questions": [
        {"q": "Which is the equality operator?", "options": ["=", "==", "!=", "=>"], "correct": 1},
        {"q": "What does 'and' do?", "options": ["OR logic", "AND logic", "NOT logic", "Adds"], "correct": 1},
        {"q": "What is the result of 5 > 3?", "options": ["True", "False", "5", "3"], "correct": 0},
        {"q": "What keyword checks a condition?", "options": ["when", "if", "check", "case"], "correct": 1},
        {"q": "What does != mean?", "options": ["Equals", "Not equals", "Greater", "Less"], "correct": 1},
        {"q": "What runs if 'if' is False?", "options": ["then", "else", "elif only", "finally"], "correct": 1},
        {"q": "What does not True evaluate to?", "options": ["True", "False", "None", "Error"], "correct": 1},
        {"q": "What is 5 >= 5?", "options": ["True", "False", "Error", "5"], "correct": 0},
        {"q": "What does 'or' return if both are False?", "options": ["True", "False", "None", "Error"], "correct": 1},
        {"q": "Which checks multiple conditions in order?", "options": ["elif", "else", "loop", "switch"], "correct": 0},
    ]},
    6: {"topic": "Loops — Basics", "questions": [
        {"q": "Which loop repeats a fixed number of times easily?", "options": ["while", "for", "repeat", "loop"], "correct": 1},
        {"q": "What does range(3) produce?", "options": ["1,2,3", "0,1,2", "0,1,2,3", "3"], "correct": 1},
        {"q": "Which keyword exits a loop early?", "options": ["stop", "exit", "break", "end"], "correct": 2},
        {"q": "Which skips to the next iteration?", "options": ["skip", "continue", "next", "pass"], "correct": 1},
        {"q": "How many times does 'for i in range(5)' run?", "options": ["4", "5", "6", "0"], "correct": 1},
        {"q": "A while loop runs while its condition is...", "options": ["False", "True", "None", "Zero"], "correct": 1},
        {"q": "What does range(1,4) give?", "options": ["1,2,3", "1,2,3,4", "0,1,2,3", "1,4"], "correct": 0},
        {"q": "What can cause an infinite while loop?", "options": ["break", "Condition never False", "range()", "continue"], "correct": 1},
        {"q": "Can you loop over a string?", "options": ["Yes", "No", "Only with index", "Only numbers"], "correct": 0},
        {"q": "What does range(0,10,2) step by?", "options": ["1", "2", "10", "0"], "correct": 1},
    ]},
    7: {"topic": "Dictionaries", "questions": [
        {"q": "What does a dictionary store?", "options": ["Only values", "Key-value pairs", "Only keys", "Indexes"], "correct": 1},
        {"q": "How do you create an empty dict?", "options": ["[]", "{}", "()", "dict[]"], "correct": 1},
        {"q": "How do you access value for key 'a'?", "options": ["d.a", "d['a']", "d(a)", "d->a"], "correct": 1},
        {"q": "How do you get all keys?", "options": ["d.keys()", "d.all()", "keys(d)", "d.key"], "correct": 0},
        {"q": "Can dict keys be duplicated?", "options": ["Yes", "No", "Sometimes", "Only strings"], "correct": 1},
        {"q": "How do you add a new key-value?", "options": ["d.add()", "d['k']=v", "d.append()", "d.push()"], "correct": 1},
        {"q": "What does d.get('x') return if 'x' missing?", "options": ["Error", "None", "0", "''"], "correct": 1},
        {"q": "How do you get all values?", "options": ["d.values()", "d.vals()", "values(d)", "d.value"], "correct": 0},
        {"q": "Are dictionary values mutable?", "options": ["Yes", "No", "Only ints", "Only strings"], "correct": 0},
        {"q": "How do you delete a key?", "options": ["del d['k']", "d.cut('k')", "remove d['k']", "d.del('k')"], "correct": 0},
    ]},
    8: {"topic": "Functions — Basics", "questions": [
        {"q": "What keyword returns a value from a function?", "options": ["give", "return", "output", "send"], "correct": 1},
        {"q": "What are values passed to a function called?", "options": ["returns", "arguments", "outputs", "loops"], "correct": 1},
        {"q": "What does a function with no return give back?", "options": ["0", "None", "Error", "Empty string"], "correct": 1},
        {"q": "How do you call a function named greet?", "options": ["greet", "greet()", "call greet", "run greet"], "correct": 1},
        {"q": "What is a default parameter?", "options": ["A required value", "A preset value if none given", "A return type", "A loop"], "correct": 1},
        {"q": "Can a function call itself?", "options": ["Yes (recursion)", "No", "Only twice", "Only loops can"], "correct": 0},
        {"q": "What does 'def add(a, b): return a+b' do with add(2,3)?", "options": ["5", "23", "Error", "None"], "correct": 0},
        {"q": "Why use functions?", "options": ["Reuse code", "Slow code", "Use more memory", "Avoid logic"], "correct": 0},
        {"q": "What is *args used for?", "options": ["One value", "Variable number of args", "Keyword args", "Return values"], "correct": 1},
        {"q": "What scope are variables inside a function?", "options": ["Global", "Local", "Universal", "Static"], "correct": 1},
    ]},
    9: {"topic": "Tuples & Sets", "questions": [
        {"q": "Are tuples mutable?", "options": ["Yes", "No", "Sometimes", "Only numbers"], "correct": 1},
        {"q": "How do you create a tuple?", "options": ["[1,2]", "(1,2)", "{1,2}", "<1,2>"], "correct": 1},
        {"q": "What does a set NOT allow?", "options": ["Numbers", "Duplicates", "Strings", "Iteration"], "correct": 1},
        {"q": "How do you create an empty set?", "options": ["{}", "set()", "[]", "()"], "correct": 1},
        {"q": "Are sets ordered?", "options": ["Yes", "No", "Always", "Only ints"], "correct": 1},
        {"q": "What does {1,2} & {2,3} give?", "options": ["{2}", "{1,2,3}", "{1,3}", "{}"], "correct": 0},
        {"q": "Can you index a set with set[0]?", "options": ["Yes", "No", "Only first", "Only last"], "correct": 1},
        {"q": "What does {1,2} | {2,3} give?", "options": ["{2}", "{1,2,3}", "{1,3}", "{}"], "correct": 1},
        {"q": "Why use a tuple over a list?", "options": ["Faster & immutable", "More memory", "Can be changed", "Allows duplicates only"], "correct": 0},
        {"q": "How do you add to a set?", "options": [".append()", ".add()", ".push()", ".insert()"], "correct": 1},
    ]},
    10: {"topic": "Review — Beginner Mix", "questions": [
        {"q": "What is the output of print(type([]))?", "options": ["<class 'list'>", "<class 'dict'>", "<class 'set'>", "<class 'tuple'>"], "correct": 0},
        {"q": "What does bool(0) return?", "options": ["True", "False", "0", "None"], "correct": 1},
        {"q": "What does 'abc'.index('b') return?", "options": ["0", "1", "2", "Error"], "correct": 1},
        {"q": "What is [x for x in range(3)]?", "options": ["[0,1,2]", "[1,2,3]", "[0,1,2,3]", "Error"], "correct": 0},
        {"q": "What does dict(a=1).keys() contain?", "options": ["[1]", "['a']", "['a',1]", "Error"], "correct": 1},
        {"q": "What is 'hello'.count('l')?", "options": ["1", "2", "3", "0"], "correct": 1},
        {"q": "What does sorted([3,1,2]) return?", "options": ["[3,2,1]", "[1,2,3]", "[2,1,3]", "Error"], "correct": 1},
        {"q": "What is max([4,7,2])?", "options": ["4", "7", "2", "13"], "correct": 1},
        {"q": "What does list('ab') give?", "options": ["['ab']", "['a','b']", "'ab'", "Error"], "correct": 1},
        {"q": "What does 5 == 5.0 return?", "options": ["True", "False", "Error", "None"], "correct": 0},
    ]},
11: {"topic": "Functions — Intermediate", "questions": [
        {"q": "What does a lambda function do?", "options": ["Loops", "Anonymous one-line function", "Imports modules", "Defines a class"], "correct": 1},
        {"q": "What does **kwargs collect?", "options": ["Positional args", "Keyword args as a dict", "Lists", "Tuples"], "correct": 1},
        {"q": "What is returned by: (lambda x: x*2)(5)?", "options": ["10", "5", "25", "Error"], "correct": 0},
        {"q": "Can a function return multiple values?", "options": ["No", "Yes, as a tuple", "Only with lists", "Only one"], "correct": 1},
        {"q": "What does map(f, lst) do?", "options": ["Sorts lst", "Applies f to each item", "Filters lst", "Reverses lst"], "correct": 1},
        {"q": "What does filter() keep?", "options": ["All items", "Items where func is True", "First item", "Last item"], "correct": 1},
        {"q": "What is a closure?", "options": ["A loop", "Function remembering enclosing scope", "A class", "An import"], "correct": 1},
        {"q": "What does a decorator do?", "options": ["Deletes a function", "Wraps/modifies a function", "Loops a function", "Prints it"], "correct": 1},
        {"q": "What scope keyword modifies a global inside a function?", "options": ["local", "global", "extern", "static"], "correct": 1},
        {"q": "What does reduce() do?", "options": ["Splits a list", "Combines items into one value", "Sorts", "Filters"], "correct": 1},
    ]},
    12: {"topic": "List Comprehensions", "questions": [
        {"q": "What does [x*2 for x in range(3)] give?", "options": ["[0,2,4]", "[2,4,6]", "[0,1,2]", "Error"], "correct": 0},
        {"q": "What does [x for x in range(5) if x%2==0] give?", "options": ["[0,2,4]", "[1,3]", "[0,1,2,3,4]", "[2,4]"], "correct": 0},
        {"q": "Comprehensions are generally ___ than loops.", "options": ["Slower", "Faster/concise", "Buggier", "Longer"], "correct": 1},
        {"q": "What does {x for x in [1,1,2]} give?", "options": ["{1,1,2}", "{1,2}", "[1,2]", "Error"], "correct": 1},
        {"q": "What does {k:v for k,v in [('a',1)]} give?", "options": ["{'a':1}", "['a',1]", "('a',1)", "Error"], "correct": 0},
        {"q": "Can comprehensions be nested?", "options": ["No", "Yes", "Only twice", "Only lists"], "correct": 1},
        {"q": "What does [x+y for x in [1] for y in [2,3]] give?", "options": ["[3,4]", "[1,2,3]", "[3]", "Error"], "correct": 0},
        {"q": "What type is (x for x in range(3))?", "options": ["list", "generator", "tuple", "set"], "correct": 1},
        {"q": "Why use a generator over a list?", "options": ["Uses less memory", "Always faster", "Stores all at once", "Allows duplicates"], "correct": 0},
        {"q": "What does [s.upper() for s in ['a','b']] give?", "options": ["['A','B']", "['a','b']", "'AB'", "Error"], "correct": 0},
    ]},
    13: {"topic": "Error Handling", "questions": [
        {"q": "Which block catches exceptions?", "options": ["catch", "except", "rescue", "handle"], "correct": 1},
        {"q": "Which block always runs?", "options": ["else", "finally", "always", "ensure"], "correct": 1},
        {"q": "What does 'raise' do?", "options": ["Catches an error", "Throws an error", "Ignores an error", "Logs an error"], "correct": 1},
        {"q": "What error for dividing by zero?", "options": ["ValueError", "ZeroDivisionError", "TypeError", "KeyError"], "correct": 1},
        {"q": "What error for missing dict key?", "options": ["KeyError", "IndexError", "NameError", "ValueError"], "correct": 0},
        {"q": "What error for list[99] when out of range?", "options": ["KeyError", "IndexError", "RangeError", "TypeError"], "correct": 1},
        {"q": "Where does code run if no exception occurs?", "options": ["except", "else", "finally", "try"], "correct": 1},
        {"q": "Can you catch multiple exceptions?", "options": ["No", "Yes", "Only one", "Only built-in"], "correct": 1},
        {"q": "What error for int('abc')?", "options": ["ValueError", "KeyError", "IndexError", "SyntaxError"], "correct": 0},
        {"q": "What is a custom exception made from?", "options": ["A function", "A class inheriting Exception", "A loop", "A dict"], "correct": 1},
    ]},
    14: {"topic": "Modules & Imports", "questions": [
        {"q": "How do you import the math module?", "options": ["include math", "import math", "use math", "require math"], "correct": 1},
        {"q": "How do you import only sqrt from math?", "options": ["from math import sqrt", "import sqrt", "import math.sqrt only", "use sqrt"], "correct": 0},
        {"q": "What does 'import math as m' allow?", "options": ["m.sqrt()", "math.m()", "sqrt.m()", "Nothing"], "correct": 0},
        {"q": "What is pip used for?", "options": ["Run code", "Install packages", "Debug", "Compile"], "correct": 1},
        {"q": "What does __name__ == '__main__' check?", "options": ["File is imported", "File is run directly", "File has errors", "File is empty"], "correct": 1},
        {"q": "What is a package?", "options": ["A single file", "A folder of modules", "A variable", "A loop"], "correct": 1},
        {"q": "Which module handles random numbers?", "options": ["rand", "random", "rnd", "numbers"], "correct": 1},
        {"q": "Which module handles dates?", "options": ["time", "datetime", "calendar only", "clock"], "correct": 1},
        {"q": "Which module handles JSON?", "options": ["json", "data", "parse", "obj"], "correct": 0},
        {"q": "Which module handles file paths cleanly?", "options": ["os/pathlib", "files", "dir", "path only"], "correct": 0},
    ]},
    15: {"topic": "File Handling", "questions": [
        {"q": "How do you open a file for reading?", "options": ["open(f,'r')", "open(f,'w')", "read(f)", "file(f)"], "correct": 0},
        {"q": "What mode appends to a file?", "options": ["'r'", "'w'", "'a'", "'x'"], "correct": 2},
        {"q": "What does 'with open()' guarantee?", "options": ["Faster reads", "File auto-closes", "No errors", "Bigger files"], "correct": 1},
        {"q": "What does .read() return?", "options": ["A list", "Entire content as string", "One line", "A dict"], "correct": 1},
        {"q": "What does .readlines() return?", "options": ["A string", "A list of lines", "One char", "A dict"], "correct": 1},
        {"q": "What mode overwrites a file?", "options": ["'r'", "'w'", "'a'", "'b'"], "correct": 1},
        {"q": "How do you write to a file?", "options": [".write()", ".print()", ".put()", ".save()"], "correct": 0},
        {"q": "What does 'b' mode mean?", "options": ["Backup", "Binary", "Big", "Buffer"], "correct": 1},
        {"q": "What happens if you open a missing file in 'r'?", "options": ["Creates it", "FileNotFoundError", "Returns None", "Empty string"], "correct": 1},
        {"q": "How do you read one line?", "options": [".readline()", ".read(1)", ".line()", ".next()"], "correct": 0},
    ]},
    16: {"topic": "Algorithms — Intro", "questions": [
        {"q": "What is an algorithm?", "options": ["A bug", "A step-by-step procedure", "A variable", "A loop only"], "correct": 1},
        {"q": "Linear search checks items...", "options": ["Randomly", "One by one", "Backwards only", "In pairs"], "correct": 1},
        {"q": "What does swapping two variables need (classically)?", "options": ["A temp variable or tuple unpack", "A loop", "A function", "A class"], "correct": 0},
        {"q": "What is the first step to sum a list manually?", "options": ["Set total=0", "Sort it", "Reverse it", "Print it"], "correct": 0},
        {"q": "What does counting occurrences require?", "options": ["A counter variable", "A class", "Two files", "A set only"], "correct": 0},
        {"q": "Finding the max requires comparing each item to...", "options": ["Zero", "Current max", "The last item", "Nothing"], "correct": 1},
        {"q": "Reversing a list in place can use...", "options": ["Two pointers", "A dict", "A file", "Recursion only"], "correct": 0},
        {"q": "What is pseudocode?", "options": ["Broken code", "Plain-language algorithm steps", "A language", "A bug"], "correct": 1},
        {"q": "Checking if a number is even uses...", "options": ["n % 2 == 0", "n / 2", "n * 2", "n ** 2"], "correct": 0},
        {"q": "What makes an algorithm 'correct'?", "options": ["It's short", "It produces right output for all inputs", "It's fast", "It uses loops"], "correct": 1},
    ]},
    17: {"topic": "Iterators & Generators", "questions": [
        {"q": "What does 'yield' create?", "options": ["A list", "A generator", "A class", "A loop"], "correct": 1},
        {"q": "What does next() do on an iterator?", "options": ["Resets it", "Gets next value", "Ends it", "Reverses it"], "correct": 1},
        {"q": "What error when an iterator is exhausted?", "options": ["StopIteration", "EndError", "KeyError", "ValueError"], "correct": 0},
        {"q": "Generators compute values...", "options": ["All at once", "Lazily/on demand", "Never", "Backwards"], "correct": 1},
        {"q": "What makes an object iterable?", "options": ["__iter__ method", "__add__", "__str__", "__len__ only"], "correct": 0},
        {"q": "Can you loop a generator twice?", "options": ["Yes, freely", "No, it's exhausted", "Only ints", "Always"], "correct": 1},
        {"q": "What does iter() return?", "options": ["A list", "An iterator", "A dict", "A number"], "correct": 1},
        {"q": "Generators are good for...", "options": ["Small fixed data", "Large/streaming data", "Sorting", "Nothing"], "correct": 1},
        {"q": "What is enumerate() used for?", "options": ["Index + value pairs", "Sorting", "Filtering", "Reversing"], "correct": 0},
        {"q": "What does zip([1,2],[3,4]) give?", "options": ["[(1,3),(2,4)]", "[1,2,3,4]", "[(1,2),(3,4)]", "Error"], "correct": 0},
    ]},
    18: {"topic": "Recursion — Intro", "questions": [
        {"q": "What is recursion?", "options": ["A loop", "A function calling itself", "An import", "A class"], "correct": 1},
        {"q": "What does every recursion need?", "options": ["A base case", "Two files", "A global", "A set"], "correct": 0},
        {"q": "What happens without a base case?", "options": ["Returns 0", "Infinite recursion/stack overflow", "Nothing", "Sorts"], "correct": 1},
        {"q": "Factorial of 0 is...", "options": ["0", "1", "Undefined", "Error"], "correct": 1},
        {"q": "Recursion uses which memory structure?", "options": ["Heap only", "Call stack", "Queue", "File"], "correct": 1},
        {"q": "factorial(3) = 3 * ?", "options": ["factorial(2)", "factorial(3)", "factorial(0)", "3"], "correct": 0},
        {"q": "Fibonacci(n) typically = ?", "options": ["fib(n-1)+fib(n-2)", "fib(n)*2", "n+1", "fib(n+1)"], "correct": 0},
        {"q": "Recursion can often be replaced by...", "options": ["Loops", "Classes", "Imports", "Files"], "correct": 0},
        {"q": "What limits recursion depth in Python?", "options": ["Memory only", "Recursion limit (~1000)", "No limit", "CPU speed"], "correct": 1},
        {"q": "Naive recursive Fibonacci is slow because of...", "options": ["Repeated subproblems", "Too few calls", "No base case", "Sorting"], "correct": 0},
    ]},
    19: {"topic": "Big-O — Intro", "questions": [
        {"q": "What does Big-O measure?", "options": ["Code length", "Growth of time/space with input", "Bugs", "Memory color"], "correct": 1},
        {"q": "What is the complexity of accessing list[i]?", "options": ["O(1)", "O(n)", "O(n²)", "O(log n)"], "correct": 0},
        {"q": "Linear search is...", "options": ["O(1)", "O(n)", "O(n²)", "O(log n)"], "correct": 1},
        {"q": "A single loop over n items is...", "options": ["O(1)", "O(n)", "O(n²)", "O(log n)"], "correct": 1},
        {"q": "Nested loops over n items are usually...", "options": ["O(n)", "O(n²)", "O(1)", "O(log n)"], "correct": 1},
        {"q": "Binary search is...", "options": ["O(n)", "O(log n)", "O(n²)", "O(1)"], "correct": 1},
        {"q": "Which is fastest for large n?", "options": ["O(n²)", "O(n)", "O(log n)", "O(n log n)"], "correct": 2},
        {"q": "O(1) means...", "options": ["Constant time", "One second", "One loop", "One item"], "correct": 0},
        {"q": "Big-O describes the ___ case usually.", "options": ["Best", "Worst", "Average only", "Random"], "correct": 1},
        {"q": "Which is worse: O(n) or O(n²)?", "options": ["O(n)", "O(n²)", "Same", "Depends on color"], "correct": 1},
    ]},
    20: {"topic": "Review — Intermediate Mix", "questions": [
        {"q": "What does list(map(str,[1,2])) give?", "options": ["['1','2']", "[1,2]", "'12'", "Error"], "correct": 0},
        {"q": "What does sum(x for x in range(4)) give?", "options": ["6", "10", "4", "0"], "correct": 0},
        {"q": "What does sorted([3,1,2], reverse=True) give?", "options": ["[1,2,3]", "[3,2,1]", "[2,1,3]", "Error"], "correct": 1},
        {"q": "What does {**{'a':1},**{'b':2}} give?", "options": ["{'a':1,'b':2}", "{'a':1}", "Error", "['a','b']"], "correct": 0},
        {"q": "What does 'a-b-c'.split('-') give?", "options": ["['a','b','c']", "'abc'", "['a-b-c']", "Error"], "correct": 0},
        {"q": "What does any([False,True]) return?", "options": ["True", "False", "Error", "None"], "correct": 0},
        {"q": "What does all([True,False]) return?", "options": ["True", "False", "Error", "None"], "correct": 1},
        {"q": "What does len(set([1,1,2,3])) give?", "options": ["4", "3", "2", "1"], "correct": 1},
        {"q": "What does [1,2,3][::-1] give?", "options": ["[1,2,3]", "[3,2,1]", "[1,3]", "Error"], "correct": 1},
        {"q": "What does enumerate(['a']) yield first?", "options": ["(0,'a')", "('a',0)", "(1,'a')", "'a'"], "correct": 0},
    ]}
    21: {"topic": "Dictionaries — Advanced", "questions": [
        {"q": "What does d.items() return?", "options": ["Keys only", "Key-value pairs", "Values only", "Length"],
         "correct": 1},
        {"q": "What does d.setdefault('k',0) do?",
         "options": ["Deletes 'k'", "Returns 'k' or sets it to 0", "Clears dict", "Sorts dict"], "correct": 1},
        {"q": "How do you merge dicts in Python 3.9+?", "options": ["d1 + d2", "d1 | d2", "d1 & d2", "d1 - d2"],
         "correct": 1},
        {"q": "What does d.pop('k') do?", "options": ["Adds 'k'", "Removes and returns 'k'", "Sorts", "Copies"],
         "correct": 1},
        {"q": "Are dicts ordered in Python 3.7+?", "options": ["No", "Yes (insertion order)", "Randomly", "Reverse"],
         "correct": 1},
        {"q": "What is a dict comprehension?", "options": ["{k:v for ...}", "[k:v for ...]", "(k:v for ...)", "<k:v>"],
         "correct": 0},
        {"q": "What does d.update({'a':2}) do?",
         "options": ["Deletes 'a'", "Adds/overwrites 'a'", "Sorts", "Returns 'a'"], "correct": 1},
        {"q": "Which can be a dict key?", "options": ["A list", "A tuple", "A set", "A dict"], "correct": 1},
        {"q": "What does d.clear() do?", "options": ["Removes all items", "Removes one", "Sorts", "Copies"],
         "correct": 0},
        {"q": "What does Counter from collections do?",
         "options": ["Sorts", "Counts occurrences", "Reverses", "Filters"], "correct": 1},
    ]},
    22: {"topic": "Sets — Advanced", "questions": [
        {"q": "What does set1 - set2 give?", "options": ["Union", "Difference", "Intersection", "Symmetric diff"],
         "correct": 1},
        {"q": "What does set1 ^ set2 give?",
         "options": ["Union", "Items in either but not both", "Intersection", "Difference"], "correct": 1},
        {"q": "What does set1.issubset(set2) check?",
         "options": ["set1 inside set2", "set2 inside set1", "Equality", "Difference"], "correct": 0},
        {"q": "Are set elements ordered?", "options": ["Yes", "No", "Always", "By value"], "correct": 1},
        {"q": "What is a frozenset?", "options": ["A mutable set", "An immutable set", "An empty set", "A dict"],
         "correct": 1},
        {"q": "Why are sets fast for membership?", "options": ["Sorted", "Hash-based", "Small", "Indexed"],
         "correct": 1},
        {"q": "What does set([1,1,2,2]) give?", "options": ["{1,1,2,2}", "{1,2}", "[1,2]", "Error"], "correct": 1},
        {"q": "What does s.discard(x) do if x missing?", "options": ["Error", "Nothing", "Adds x", "Clears s"],
         "correct": 1},
        {"q": "What does s.remove(x) do if x missing?", "options": ["Nothing", "KeyError", "Adds x", "Returns None"],
         "correct": 1},
        {"q": "Can a set contain a list?", "options": ["Yes", "No (unhashable)", "Only empty", "Only one"],
         "correct": 1},
    ]},
    23: {"topic": "OOP — Classes & Objects", "questions": [
        {"q": "What keyword defines a class?", "options": ["class", "def", "object", "struct"], "correct": 0},
        {"q": "What is __init__?", "options": ["A loop", "The constructor", "A destructor", "An import"], "correct": 1},
        {"q": "What does 'self' refer to?", "options": ["The class", "The instance", "The module", "A loop"],
         "correct": 1},
        {"q": "What is an object?", "options": ["A class blueprint", "An instance of a class", "A function", "A loop"],
         "correct": 1},
        {"q": "How do you create an instance of class Dog?", "options": ["Dog", "Dog()", "new Dog", "create Dog"],
         "correct": 1},
        {"q": "What is an attribute?", "options": ["A method", "A variable bound to an object", "A loop", "An import"],
         "correct": 1},
        {"q": "What is a method?", "options": ["A variable", "A function inside a class", "A module", "A loop"],
         "correct": 1},
        {"q": "What does __str__ control?", "options": ["Object's printable string", "Memory", "Speed", "Imports"],
         "correct": 0},
        {"q": "What are class variables shared by?",
         "options": ["One instance", "All instances", "No instances", "Modules"], "correct": 1},
        {"q": "What is a constructor's job?",
         "options": ["Destroy object", "Initialize attributes", "Print object", "Sort"], "correct": 1},
    ]},
    24: {"topic": "OOP — Inheritance", "questions": [
        {"q": "What is inheritance?",
         "options": ["Copying files", "A class deriving from another", "A loop", "An import"], "correct": 1},
        {"q": "How do you inherit from class Animal?",
         "options": ["class Dog(Animal)", "class Dog:Animal", "Dog extends Animal", "inherit Animal"], "correct": 0},
        {"q": "What does super() do?", "options": ["Deletes parent", "Calls parent methods", "Sorts", "Imports"],
         "correct": 1},
        {"q": "What is method overriding?",
         "options": ["Deleting a method", "Redefining a parent method", "Copying", "Looping"], "correct": 1},
        {"q": "What is the parent class also called?", "options": ["Child", "Base/super class", "Module", "Loop"],
         "correct": 1},
        {"q": "Can Python do multiple inheritance?", "options": ["No", "Yes", "Only two", "Only one"], "correct": 1},
        {"q": "What is polymorphism?", "options": ["One name, many forms", "One file", "A loop", "An error"],
         "correct": 0},
        {"q": "What does isinstance(x, Dog) check?",
         "options": ["x's value", "If x is a Dog instance", "x's length", "x's type name"], "correct": 1},
        {"q": "What does issubclass(Dog, Animal) check?",
         "options": ["Dog is an Animal subclass", "Instances", "Values", "Length"], "correct": 0},
        {"q": "What is the MRO?",
         "options": ["Method Resolution Order", "Memory Read Op", "Module Run Order", "Max Recursion"], "correct": 0},
    ]},
    25: {"topic": "OOP — Encapsulation", "questions": [
        {"q": "What does a leading underscore _x signal?",
         "options": ["Public", "Internal/protected by convention", "Constant", "Global"], "correct": 1},
        {"q": "What does double underscore __x trigger?",
         "options": ["Name mangling", "Deletion", "Global scope", "A loop"], "correct": 0},
        {"q": "What is encapsulation?", "options": ["Bundling data + methods", "Copying", "Looping", "Importing"],
         "correct": 0},
        {"q": "What is a @property used for?",
         "options": ["A loop", "Getter-like access to a method", "An import", "A class"], "correct": 1},
        {"q": "What is a getter?", "options": ["Sets a value", "Retrieves a value", "Deletes", "Loops"], "correct": 1},
        {"q": "What is a setter?", "options": ["Retrieves", "Sets/validates a value", "Deletes", "Imports"],
         "correct": 1},
        {"q": "What is a @staticmethod?", "options": ["Needs self", "No self/cls needed", "Needs cls only", "A loop"],
         "correct": 1},
        {"q": "What is a @classmethod's first arg?", "options": ["self", "cls", "obj", "this"], "correct": 1},
        {"q": "Why hide attributes?",
         "options": ["Slower code", "Control & protect data", "More memory", "Fewer methods"], "correct": 1},
        {"q": "Does Python enforce strict privacy?",
         "options": ["Yes", "No, by convention", "Always", "Never allows access"], "correct": 1},
    ]},
    26: {"topic": "Searching Algorithms", "questions": [
        {"q": "Linear search works on...", "options": ["Sorted only", "Any list", "Sets only", "Dicts only"],
         "correct": 1},
        {"q": "Binary search requires the list to be...", "options": ["Sorted", "Unsorted", "Empty", "Reversed"],
         "correct": 0},
        {"q": "Binary search complexity?", "options": ["O(n)", "O(log n)", "O(n²)", "O(1)"], "correct": 1},
        {"q": "Binary search repeatedly checks the...", "options": ["First", "Middle", "Last", "Random"], "correct": 1},
        {"q": "If target < middle, search the...", "options": ["Right half", "Left half", "Whole list", "Nothing"],
         "correct": 1},
        {"q": "Linear search worst case?", "options": ["O(1)", "O(n)", "O(log n)", "O(n²)"], "correct": 1},
        {"q": "Best case for linear search?", "options": ["O(1) (first item)", "O(n)", "O(log n)", "O(n²)"],
         "correct": 0},
        {"q": "Binary search on n=8 takes at most ~?", "options": ["8 steps", "3 steps", "1 step", "16 steps"],
         "correct": 1},
        {"q": "Which is faster on large sorted data?", "options": ["Linear", "Binary", "Same", "Neither"],
         "correct": 1},
        {"q": "What does search return when not found (common)?", "options": ["-1 or None", "0", "The list", "True"],
         "correct": 0},
    ]},
    27: {"topic": "Sorting — Basics", "questions": [
        {"q": "Bubble sort repeatedly swaps...",
         "options": ["Random items", "Adjacent out-of-order items", "First and last", "Nothing"], "correct": 1},
        {"q": "Bubble sort worst-case complexity?", "options": ["O(n)", "O(n²)", "O(log n)", "O(1)"], "correct": 1},
        {"q": "Selection sort repeatedly finds the...", "options": ["Middle", "Min (or max)", "First", "Random"],
         "correct": 1},
        {"q": "Insertion sort builds the sorted list...",
         "options": ["All at once", "One item at a time", "Backwards", "Randomly"], "correct": 1},
        {"q": "Python's built-in sort is called...", "options": ["Bubblesort", "Timsort", "Quicksort", "Heapsort"],
         "correct": 1},
        {"q": "What does .sort() return?", "options": ["A new list", "None (sorts in place)", "The length", "A copy"],
         "correct": 1},
        {"q": "What does sorted() return?", "options": ["None", "A new sorted list", "In-place", "Length"],
         "correct": 1},
        {"q": "Insertion sort is efficient for...", "options": ["Large random", "Small/nearly-sorted", "Never", "Sets"],
         "correct": 1},
        {"q": "A 'stable' sort preserves...", "options": ["Equal elements' order", "Memory", "Speed", "Nothing"],
         "correct": 0},
        {"q": "Which is generally fastest for big data?",
         "options": ["Bubble", "Selection", "Merge/Quick (O(n log n))", "Insertion"], "correct": 2},
    ]},
    28: {"topic": "Stacks", "questions": [
        {"q": "A stack follows which order?", "options": ["FIFO", "LIFO", "Random", "Sorted"], "correct": 1},
        {"q": "Adding to a stack is called...", "options": ["enqueue", "push", "insert", "add"], "correct": 1},
        {"q": "Removing from a stack is called...", "options": ["dequeue", "pop", "shift", "cut"], "correct": 1},
        {"q": "Which Python type works as a stack?", "options": ["list", "set", "dict", "tuple"], "correct": 0},
        {"q": "list.pop() removes from the...", "options": ["Front", "End", "Middle", "Random"], "correct": 1},
        {"q": "Stacks are used in...", "options": ["Undo features", "Sorting only", "Networking only", "Nothing"],
         "correct": 0},
        {"q": "What is 'top' of a stack?", "options": ["First added", "Most recently added", "Random", "Middle"],
         "correct": 1},
        {"q": "Function call management uses a...", "options": ["Queue", "Call stack", "Set", "Dict"], "correct": 1},
        {"q": "Push/pop complexity on a list?", "options": ["O(1)", "O(n)", "O(log n)", "O(n²)"], "correct": 0},
        {"q": "Popping an empty stack causes...", "options": ["Nothing", "An error", "Returns 0", "Returns None"],
         "correct": 1},
    ]},
    29: {"topic": "Queues", "questions": [
        {"q": "A queue follows which order?", "options": ["LIFO", "FIFO", "Random", "Sorted"], "correct": 1},
        {"q": "Adding to a queue is called...", "options": ["push", "enqueue", "pop", "cut"], "correct": 1},
        {"q": "Removing from a queue is called...", "options": ["enqueue", "dequeue", "push", "add"], "correct": 1},
        {"q": "Which is efficient for queues in Python?", "options": ["list", "collections.deque", "set", "dict"],
         "correct": 1},
        {"q": "Why is list.pop(0) slow?", "options": ["O(n) shifting", "O(1)", "It errors", "It sorts"], "correct": 0},
        {"q": "deque.popleft() complexity?", "options": ["O(1)", "O(n)", "O(log n)", "O(n²)"], "correct": 0},
        {"q": "Queues are used in...", "options": ["Task scheduling", "Undo only", "Sorting only", "Nothing"],
         "correct": 0},
        {"q": "What is the 'front' of a queue?",
         "options": ["Last added", "First added (next out)", "Random", "Middle"], "correct": 1},
        {"q": "A priority queue serves by...", "options": ["Arrival order", "Priority/value", "Random", "Reverse"],
         "correct": 1},
        {"q": "Which module has a Queue class?", "options": ["queue", "stack", "list", "array"], "correct": 0},
    ]},
    30: {"topic": "Review — OOP & Structures", "questions": [
        {"q": "What does isinstance(5, int) return?", "options": ["True", "False", "Error", "None"], "correct": 0},
        {"q": "Which structure is LIFO?", "options": ["Queue", "Stack", "Dict", "Set"], "correct": 1},
        {"q": "Which structure is FIFO?", "options": ["Stack", "Queue", "Set", "Tuple"], "correct": 1},
        {"q": "What does super().__init__() do?",
         "options": ["Deletes parent", "Calls parent constructor", "Loops", "Sorts"], "correct": 1},
        {"q": "Binary search needs data to be...", "options": ["Sorted", "Reversed", "Empty", "A set"], "correct": 0},
        {"q": "deque is best for...", "options": ["Fast ends ops", "Sorting", "Hashing", "Nothing"], "correct": 0},
        {"q": "What complexity is bubble sort?", "options": ["O(n)", "O(n²)", "O(log n)", "O(1)"], "correct": 1},
        {"q": "What defines a class blueprint?", "options": ["object", "class", "def", "self"], "correct": 1},
        {"q": "What does a frozenset NOT allow?", "options": ["Iteration", "Modification", "Membership", "Length"],
         "correct": 1},
        {"q": "Polymorphism means one interface, many...", "options": ["Errors", "Implementations", "Files", "Loops"],
         "correct": 1},
    ]},
}