"""90-day quiz question bank. 10 questions per day, basic to expert.

TO ADD A DAY: copy a day block, change the number, write 10 questions.
Each question: {"q": "...", "options": [4 choices], "correct": index 0-3}
The engine auto-detects any day you add here. No other code changes needed.

Curve: Days 1-20 Beginner, 21-45 Intermediate, 46-70 Advanced, 71-90 Expert.
"""

QUIZ_DATA = {
    1: {"topic": "Python Basics — Intro", "questions": [
        {"q": "Which keyword defines a function in Python?", "options": ["func", "def", "function", "lambda"], "correct": 1},
        {"q": "How do you write a single-line comment?", "options": ["//", "#", "<!--", "/*"], "correct": 1},
        {"q": "Which is a valid variable name?", "options": ["2name", "my-name", "my_name", "my name"], "correct": 2},
        {"q": "What does print() do?", "options": ["Reads input", "Outputs to screen", "Deletes a file", "Adds numbers"], "correct": 1},
        {"q": "Which symbol is used for assignment?", "options": ["==", "=>", "=", ":="], "correct": 2},
        {"q": "What is the output of: print(2 + 3)?", "options": ["23", "5", "2 + 3", "Error"], "correct": 1},
        {"q": "Which is NOT a Python data type?", "options": ["int", "float", "char", "str"], "correct": 2},
        {"q": "How do you create a string?", "options": ["Quotes", "Brackets", "Braces", "Parentheses"], "correct": 0},
        {"q": "What does type() return?", "options": ["The value", "The data type", "The length", "The memory"], "correct": 1},
        {"q": "Python is which kind of language?", "options": ["Compiled only", "Interpreted", "Assembly", "Machine code"], "correct": 1},
    ]},
    2: {"topic": "Variables & Data Types", "questions": [
        {"q": "What type is True?", "options": ["int", "bool", "str", "float"], "correct": 1},
        {"q": "What is 7 // 2?", "options": ["3.5", "3", "4", "3.0"], "correct": 1},
        {"q": "What is 2 ** 3?", "options": ["6", "8", "9", "5"], "correct": 1},
        {"q": "What type is 3.14?", "options": ["int", "float", "str", "bool"], "correct": 1},
        {"q": "How do you convert '5' to an integer?", "options": ["str(5)", "int('5')", "float('5')", "bool('5')"], "correct": 1},
        {"q": "What is the result of 10 % 3?", "options": ["3", "1", "0", "3.33"], "correct": 1},
        {"q": "Which creates a float?", "options": ["x = 5", "x = '5'", "x = 5.0", "x = True"], "correct": 2},
        {"q": "What is None in Python?", "options": ["Zero", "Empty string", "Absence of value", "False"], "correct": 2},
        {"q": "What does str(42) produce?", "options": ["42", "'42'", "Error", "4.2"], "correct": 1},
        {"q": "Which is a valid boolean?", "options": ["true", "TRUE", "True", "yes"], "correct": 2},
    ]},
    3: {"topic": "Strings", "questions": [
        {"q": "How do you get the length of a string s?", "options": ["s.length", "len(s)", "size(s)", "s.size()"], "correct": 1},
        {"q": "What does 'abc'[0] return?", "options": ["a", "b", "c", "Error"], "correct": 0},
        {"q": "What does 'Hello'.upper() return?", "options": ["hello", "HELLO", "Hello", "hELLO"], "correct": 1},
        {"q": "How do you join 'a' and 'b'?", "options": ["'a' + 'b'", "'a' - 'b'", "'a' * 'b'", "'a' / 'b'"], "correct": 0},
        {"q": "What does 'abc'[-1] return?", "options": ["a", "c", "b", "Error"], "correct": 1},
        {"q": "What does 'Hi'.replace('i','ey') give?", "options": ["Hey", "Hi", "Hiey", "Hieey"], "correct": 0},
        {"q": "What does ' hi '.strip() return?", "options": ["' hi '", "'hi'", "'hi '", "' hi'"], "correct": 1},
        {"q": "What does 'a,b,c'.split(',') return?", "options": ["'abc'", "['a','b','c']", "('a','b','c')", "Error"], "correct": 1},
        {"q": "Are Python strings mutable?", "options": ["Yes", "No", "Sometimes", "Only short ones"], "correct": 1},
        {"q": "What does 'ab' * 3 return?", "options": ["'ababab'", "'ab3'", "Error", "'abababab'"], "correct": 0},
    ]},
    4: {"topic": "Lists — Basics", "questions": [
        {"q": "How do you create an empty list?", "options": ["[]", "{}", "()", "list{}"], "correct": 0},
        {"q": "How do you add to the end of a list?", "options": [".add()", ".append()", ".push()", ".insert()"], "correct": 1},
        {"q": "What does [1,2,3][1] return?", "options": ["1", "2", "3", "Error"], "correct": 1},
        {"q": "How do you remove the last item?", "options": [".pop()", ".remove()", ".delete()", ".cut()"], "correct": 0},
        {"q": "What does len([1,2,3]) return?", "options": ["2", "3", "4", "0"], "correct": 1},
        {"q": "Are lists mutable?", "options": ["Yes", "No", "Only numbers", "Only strings"], "correct": 0},
        {"q": "What does [1,2] + [3,4] give?", "options": ["[1,2,3,4]", "[4,6]", "Error", "[[1,2],[3,4]]"], "correct": 0},
        {"q": "How do you access the first item?", "options": ["list[1]", "list[0]", "list.first", "list(0)"], "correct": 1},
        {"q": "What does [5,3,1].sort() do?", "options": ["Reverses", "Sorts ascending", "Removes items", "Nothing"], "correct": 1},
        {"q": "What does 'x' in ['x','y'] return?", "options": ["True", "False", "0", "Error"], "correct": 0},
    ]},
    5: {"topic": "Operators & Conditionals", "questions": [
        {"q": "Which is the equality operator?", "options": ["=", "==", "!=", "=>"], "correct": 1},
        {"q": "What does 'and' do?", "options": ["OR logic", "AND logic", "NOT logic", "Adds"], "correct": 1},
        {"q": "What is the result of 5 > 3?", "options": ["True", "False", "5", "3"], "correct": 0},
        {"q": "What keyword checks a condition?", "options": ["when", "if", "check", "case"], "correct": 1},
        {"q": "What does != mean?", "options": ["Equals", "Not equals", "Greater", "Less"], "correct": 1},
        {"q": "What runs if 'if' is False?", "options": ["then", "else", "elif only", "finally"], "correct": 1},
        {"q": "What does not True evaluate to?", "options": ["True", "False", "None", "Error"], "correct": 1},
        {"q": "What is 5 >= 5?", "options": ["True", "False", "Error", "5"], "correct": 0},
        {"q": "What does 'or' return if both are False?", "options": ["True", "False", "None", "Error"], "correct": 1},
        {"q": "Which checks multiple conditions in order?", "options": ["elif", "else", "loop", "switch"], "correct": 0},
    ]},
    6: {"topic": "Loops — Basics", "questions": [
        {"q": "Which loop repeats a fixed number of times easily?", "options": ["while", "for", "repeat", "loop"], "correct": 1},
        {"q": "What does range(3) produce?", "options": ["1,2,3", "0,1,2", "0,1,2,3", "3"], "correct": 1},
        {"q": "Which keyword exits a loop early?", "options": ["stop", "exit", "break", "end"], "correct": 2},
        {"q": "Which skips to the next iteration?", "options": ["skip", "continue", "next", "pass"], "correct": 1},
        {"q": "How many times does 'for i in range(5)' run?", "options": ["4", "5", "6", "0"], "correct": 1},
        {"q": "A while loop runs while its condition is...", "options": ["False", "True", "None", "Zero"], "correct": 1},
        {"q": "What does range(1,4) give?", "options": ["1,2,3", "1,2,3,4", "0,1,2,3", "1,4"], "correct": 0},
        {"q": "What can cause an infinite while loop?", "options": ["break", "Condition never False", "range()", "continue"], "correct": 1},
        {"q": "Can you loop over a string?", "options": ["Yes", "No", "Only with index", "Only numbers"], "correct": 0},
        {"q": "What does range(0,10,2) step by?", "options": ["1", "2", "10", "0"], "correct": 1},
    ]},
    7: {"topic": "Dictionaries", "questions": [
        {"q": "What does a dictionary store?", "options": ["Only values", "Key-value pairs", "Only keys", "Indexes"], "correct": 1},
        {"q": "How do you create an empty dict?", "options": ["[]", "{}", "()", "dict[]"], "correct": 1},
        {"q": "How do you access value for key 'a'?", "options": ["d.a", "d['a']", "d(a)", "d->a"], "correct": 1},
        {"q": "How do you get all keys?", "options": ["d.keys()", "d.all()", "keys(d)", "d.key"], "correct": 0},
        {"q": "Can dict keys be duplicated?", "options": ["Yes", "No", "Sometimes", "Only strings"], "correct": 1},
        {"q": "How do you add a new key-value?", "options": ["d.add()", "d['k']=v", "d.append()", "d.push()"], "correct": 1},
        {"q": "What does d.get('x') return if 'x' missing?", "options": ["Error", "None", "0", "''"], "correct": 1},
        {"q": "How do you get all values?", "options": ["d.values()", "d.vals()", "values(d)", "d.value"], "correct": 0},
        {"q": "Are dictionary values mutable?", "options": ["Yes", "No", "Only ints", "Only strings"], "correct": 0},
        {"q": "How do you delete a key?", "options": ["del d['k']", "d.cut('k')", "remove d['k']", "d.del('k')"], "correct": 0},
    ]},
    8: {"topic": "Functions — Basics", "questions": [
        {"q": "What keyword returns a value from a function?", "options": ["give", "return", "output", "send"], "correct": 1},
        {"q": "What are values passed to a function called?", "options": ["returns", "arguments", "outputs", "loops"], "correct": 1},
        {"q": "What does a function with no return give back?", "options": ["0", "None", "Error", "Empty string"], "correct": 1},
        {"q": "How do you call a function named greet?", "options": ["greet", "greet()", "call greet", "run greet"], "correct": 1},
        {"q": "What is a default parameter?", "options": ["A required value", "A preset value if none given", "A return type", "A loop"], "correct": 1},
        {"q": "Can a function call itself?", "options": ["Yes (recursion)", "No", "Only twice", "Only loops can"], "correct": 0},
        {"q": "What does 'def add(a, b): return a+b' do with add(2,3)?", "options": ["5", "23", "Error", "None"], "correct": 0},
        {"q": "Why use functions?", "options": ["Reuse code", "Slow code", "Use more memory", "Avoid logic"], "correct": 0},
        {"q": "What is *args used for?", "options": ["One value", "Variable number of args", "Keyword args", "Return values"], "correct": 1},
        {"q": "What scope are variables inside a function?", "options": ["Global", "Local", "Universal", "Static"], "correct": 1},
    ]},
    9: {"topic": "Tuples & Sets", "questions": [
        {"q": "Are tuples mutable?", "options": ["Yes", "No", "Sometimes", "Only numbers"], "correct": 1},
        {"q": "How do you create a tuple?", "options": ["[1,2]", "(1,2)", "{1,2}", "<1,2>"], "correct": 1},
        {"q": "What does a set NOT allow?", "options": ["Numbers", "Duplicates", "Strings", "Iteration"], "correct": 1},
        {"q": "How do you create an empty set?", "options": ["{}", "set()", "[]", "()"], "correct": 1},
        {"q": "Are sets ordered?", "options": ["Yes", "No", "Always", "Only ints"], "correct": 1},
        {"q": "What does {1,2} & {2,3} give?", "options": ["{2}", "{1,2,3}", "{1,3}", "{}"], "correct": 0},
        {"q": "Can you index a set with set[0]?", "options": ["Yes", "No", "Only first", "Only last"], "correct": 1},
        {"q": "What does {1,2} | {2,3} give?", "options": ["{2}", "{1,2,3}", "{1,3}", "{}"], "correct": 1},
        {"q": "Why use a tuple over a list?", "options": ["Faster & immutable", "More memory", "Can be changed", "Allows duplicates only"], "correct": 0},
        {"q": "How do you add to a set?", "options": [".append()", ".add()", ".push()", ".insert()"], "correct": 1},
    ]},
    10: {"topic": "Review — Beginner Mix", "questions": [
        {"q": "What is the output of print(type([]))?", "options": ["<class 'list'>", "<class 'dict'>", "<class 'set'>", "<class 'tuple'>"], "correct": 0},
        {"q": "What does bool(0) return?", "options": ["True", "False", "0", "None"], "correct": 1},
        {"q": "What does 'abc'.index('b') return?", "options": ["0", "1", "2", "Error"], "correct": 1},
        {"q": "What is [x for x in range(3)]?", "options": ["[0,1,2]", "[1,2,3]", "[0,1,2,3]", "Error"], "correct": 0},
        {"q": "What does dict(a=1).keys() contain?", "options": ["[1]", "['a']", "['a',1]", "Error"], "correct": 1},
        {"q": "What is 'hello'.count('l')?", "options": ["1", "2", "3", "0"], "correct": 1},
        {"q": "What does sorted([3,1,2]) return?", "options": ["[3,2,1]", "[1,2,3]", "[2,1,3]", "Error"], "correct": 1},
        {"q": "What is max([4,7,2])?", "options": ["4", "7", "2", "13"], "correct": 1},
        {"q": "What does list('ab') give?", "options": ["['ab']", "['a','b']", "'ab'", "Error"], "correct": 1},
        {"q": "What does 5 == 5.0 return?", "options": ["True", "False", "Error", "None"], "correct": 0},
    ]},
}